# Netlify deployment configuration for Expo Web
[build]
  # The command to build your Expo web app
  command = "npx expo export:web"
  
  # The directory where the build output will be
  publish = "web-build"
  
  # Environment variables (set these in Netlify dashboard)
  # EXPO_PUBLIC_API_URL - Your backend API URL
  # EXPO_PUBLIC_SUPABASE_URL - Your Supabase project URL
  # EXPO_PUBLIC_SUPABASE_ANON_KEY - Your Supabase anon key

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

